### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Jaimer117** [SistemasTecTlaxiaco/infografia-Jaimer117-1#2]
![Gestión De Proyecto De Software](https://user-images.githubusercontent.com/80010898/132251269-36bf6f85-8155-42f3-8a45-8ee6e733d17c.png)

**Comment by Edwin-1012** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Faltan metodologías, herramientas....Bien hecho y revisado.
